// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EfbHooks from "../src/EfbHooks.res.mjs";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as EfbPairing from "../src/EfbPairing.res.mjs";
import * as EfbProvider from "../src/EfbProvider.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Demo$SharedEfb(props) {
  let alt = EfbHooks.useSimVar("ALT_FT");
  let match = EfbHooks.useUiState("page", "home");
  let setPage = match[1];
  let page = match[0];
  let conn = EfbHooks.useConnection();
  let altText = alt !== undefined ? JSON.stringify(alt) : "—";
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsxs("header", {
        children: [
          JsxRuntime.jsx("span", {
            children: `Connection: ` + conn
          }),
          JsxRuntime.jsx("span", {
            children: ` · ALT ` + altText + ` ft`
          })
        ]
      }),
      JsxRuntime.jsx("nav", {
        children: [
          "home",
          "charts",
          "perf"
        ].map(p => {
          let active = Core__Option.getOr(Core__JSON.Decode.string(page), "") === p;
          return JsxRuntime.jsx("button", {
            children: p,
            className: active ? "active" : "",
            onClick: param => setPage(p)
          }, p);
        })
      })
    ]
  });
}

let SharedEfb = {
  make: Demo$SharedEfb
};

function Demo$MirrorEntry(props) {
  let match = EfbPairing.readStored();
  if (match !== undefined) {
    return JsxRuntime.jsx(EfbProvider.make, {
      mode: {
        TAG: "Mirror",
        url: match.url,
        token: match.token
      },
      children: JsxRuntime.jsx(Demo$SharedEfb, {})
    });
  } else {
    return JsxRuntime.jsx(EfbPairing.make, {
      onPaired: param => ((window.location.reload()))
    });
  }
}

let MirrorEntry = {
  make: Demo$MirrorEntry
};

function Demo$InSimEntry(props) {
  return JsxRuntime.jsx(EfbProvider.make, {
    mode: "InSim",
    children: JsxRuntime.jsx(Demo$SharedEfb, {})
  });
}

let InSimEntry = {
  make: Demo$InSimEntry
};

export {
  SharedEfb,
  MirrorEntry,
  InSimEntry,
}
/* EfbHooks Not a pure module */
