// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EfbWs from "./EfbWs.res.mjs";
import * as React from "react";
import * as EfbStore from "./EfbStore.res.mjs";
import * as EfbProvider from "./EfbProvider.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function useStoreValue(channel, key) {
  let ctx = EfbProvider.useCtx();
  let store = ctx.store;
  let subscribe = notify => EfbStore.subscribe(store, channel, key, notify);
  let getSnapshot = () => EfbStore.read(store, channel, key);
  return React.useSyncExternalStore(subscribe, getSnapshot);
}

function useSimVar(key) {
  return useStoreValue("sim", key);
}

function useUiState(key, $$default) {
  let ctx = EfbProvider.useCtx();
  let stored = useStoreValue("ui", key);
  let value = Core__Option.getOr(stored, $$default);
  let setter = v => {
    let ws = ctx.ws;
    if (ws !== undefined) {
      return EfbWs.sendUi(ws, key, v);
    }
    let d = {};
    d[key] = v;
    EfbStore.applyDelta(ctx.store, "ui", d);
  };
  return [
    value,
    setter
  ];
}

function useCmd(name) {
  let ctx = EfbProvider.useCtx();
  return data => {
    let ws = ctx.ws;
    if (ws !== undefined) {
      return EfbWs.sendCmd(ws, name, data);
    } else {
      console.warn("efb-mirror: cmd dropped (no WS)", name);
      return;
    }
  };
}

function useCmdSubscription(name, handler) {
  let ctx = EfbProvider.useCtx();
  React.useEffect(() => {
    let ws = ctx.ws;
    if (ws !== undefined) {
      return EfbWs.onCmd(ws, name, (param, data) => handler(data));
    }
  }, [
    name,
    ctx.ws
  ]);
}

function useConnection() {
  let ctx = EfbProvider.useCtx();
  let getSnapshot = () => {
    let ws = ctx.ws;
    if (ws !== undefined) {
      return EfbWs.getConnection(ws);
    } else {
      return "InSim";
    }
  };
  let subscribe = notify => {
    let ws = ctx.ws;
    if (ws !== undefined) {
      return EfbWs.onConnectionChange(ws, notify);
    } else {
      return () => {};
    }
  };
  return React.useSyncExternalStore(subscribe, getSnapshot);
}

function usePublishSimVar(key, value) {
  let ctx = EfbProvider.useCtx();
  React.useEffect(() => {
    let d = {};
    d[key] = value;
    EfbStore.applyDelta(ctx.store, "sim", d);
    let ws = ctx.ws;
    if (ws !== undefined) {
      EfbWs.sendSim(ws, key, value);
    }
  }, [
    key,
    value
  ]);
}

export {
  useStoreValue,
  useSimVar,
  useUiState,
  useCmd,
  useCmdSubscription,
  useConnection,
  usePublishSimVar,
}
/* EfbWs Not a pure module */
