// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EfbWs from "./EfbWs.res.mjs";
import * as React from "react";
import * as EfbStore from "./EfbStore.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";
import * as JsxRuntime from "react/jsx-runtime";

let context = React.createContext({
  store: EfbStore.make(),
  ws: undefined,
  mode: "InSim"
});

let make = context.Provider;

let Provider = {
  make: make
};

function EfbProvider(props) {
  let mode = props.mode;
  let ctxRef = React.useRef(undefined);
  let c = ctxRef.current;
  let ctx;
  if (c !== undefined) {
    ctx = c;
  } else {
    let store = EfbStore.make();
    let ws;
    ws = typeof mode !== "object" ? undefined : EfbWs.make(store, mode.url, mode.token);
    let c$1 = {
      store: store,
      ws: ws,
      mode: mode
    };
    ctxRef.current = c$1;
    ctx = c$1;
  }
  React.useEffect(() => {
    let ws = ctx.ws;
    let interval = ws !== undefined ? Primitive_option.some(setInterval(() => EfbWs.sendPing(ws), 20000)) : undefined;
    return () => {
      if (interval !== undefined) {
        clearInterval(Primitive_option.valFromOption(interval));
      }
      let ws = ctx.ws;
      if (ws !== undefined) {
        return EfbWs.close(ws);
      }
    };
  }, []);
  return JsxRuntime.jsx(make, {
    value: ctx,
    children: props.children
  });
}

function useCtx() {
  return React.useContext(context);
}

let make$1 = EfbProvider;

export {
  context,
  Provider,
  make$1 as make,
  useCtx,
}
/* context Not a pure module */
