// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

let storageKey = "efb-mirror-creds";

function readStored() {
  let raw;
  try {
    raw = window.localStorage[storageKey];
  } catch (exn) {
    raw = undefined;
  }
  if (raw === undefined) {
    return;
  }
  if (raw === "") {
    return;
  }
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (exn$1) {
    parsed = null;
  }
  let o = Core__JSON.Decode.object(parsed);
  if (o === undefined) {
    return;
  }
  let url = Core__Option.getOr(Core__Option.flatMap(o["url"], Core__JSON.Decode.string), "");
  let token = Core__Option.getOr(Core__Option.flatMap(o["token"], Core__JSON.Decode.string), "");
  if (url !== "" && token !== "") {
    return {
      url: url,
      token: token
    };
  }
}

function writeStored(c) {
  let d = {};
  d["url"] = c.url;
  d["token"] = c.token;
  window.localStorage[storageKey] = JSON.stringify(d);
}

function clearStored() {
  try {
    window.localStorage[storageKey] = "";
    return;
  } catch (exn) {
    return;
  }
}

let unpairAndReload = (function() {
    try { window.localStorage.removeItem("efb-mirror-creds"); } catch (e) {}
    window.location.reload();
  });

function defaultUrlFromLocation() {
  let proto = window.location.protocol === "https:" ? "wss:" : "ws:";
  let host = window.location.host;
  return proto + `//` + host + `/ws`;
}

let _parseQueryCreds = (function(search) {
    try {
      var p = new URLSearchParams(search);
      var u = p.get("url");
      var t = p.get("token");
      if (u && t) { return { url: u, token: t }; }
      return undefined;
    } catch (e) {
      return undefined;
    }
  });

let _parseQueryCode = (function(search) {
    try {
      var p = new URLSearchParams(search);
      var c = p.get("code");
      if (c) { return c.toUpperCase(); }
      return undefined;
    } catch (e) {
      return undefined;
    }
  });

function readQueryCreds() {
  let search = window.location.search;
  if (search === "") {
    return;
  } else {
    return _parseQueryCreds(search);
  }
}

function readQueryCode() {
  let search = window.location.search;
  if (search === "") {
    return;
  } else {
    return _parseQueryCode(search);
  }
}

let redeemPairingCode = (async function(code) {
    var url = "/pair?code=" + encodeURIComponent(code);
    var res;
    try {
      res = await fetch(url, { method: "GET", credentials: "same-origin" });
    } catch (e) {
      return { TAG: "Error", _0: "Network error reaching manager" };
    }
    if (!res.ok) {
      var msg;
      if (res.status === 404) msg = "Unknown or already-used code";
      else if (res.status === 410) msg = "Code expired — generate a new one";
      else msg = "Pair failed (HTTP " + res.status + ")";
      return { TAG: "Error", _0: msg };
    }
    var body;
    try {
      body = await res.json();
    } catch (e) {
      return { TAG: "Error", _0: "Malformed pair response" };
    }
    if (!body || typeof body.token !== "string" || body.token === "") {
      return { TAG: "Error", _0: "Manager returned no token" };
    }
    var proto = window.location.protocol === "https:" ? "wss:" : "ws:";
    var host = window.location.host;
    var wsUrl = proto + "//" + host + "/ws";
    return { TAG: "Ok", _0: { url: wsUrl, token: body.token } };
  });

let stripQuery = (function() {
    var path = window.location.pathname || "/";
    window.history.replaceState(null, "", path);
  });

function EfbPairing(props) {
  let onPaired = props.onPaired;
  let match = React.useState(() => "");
  let setCode = match[1];
  let code = match[0];
  let match$1 = React.useState(() => {});
  let setError = match$1[1];
  let error = match$1[0];
  let match$2 = React.useState(() => false);
  let setBusy = match$2[1];
  let busy = match$2[0];
  let submit = async c => {
    setBusy(param => true);
    setError(param => {});
    let result = await redeemPairingCode(c);
    setBusy(param => false);
    if (result.TAG === "Ok") {
      let creds = result._0;
      writeStored(creds);
      return onPaired(creds);
    }
    let msg = result._0;
    return setError(param => msg);
  };
  let onSubmit = ev => {
    ev.preventDefault();
    let c = code.trim().toUpperCase();
    if (c === "") {
      return setError(param => "Enter the 5-character code shown in the manager");
    } else {
      submit(c);
      return;
    }
  };
  return JsxRuntime.jsxs("form", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Pair this device"
      }),
      JsxRuntime.jsx("p", {
        children: "Open the Infinity Manager on the sim host. Under Settings → EFB tablet sharing, hit \"Generate code\" and type the 5 characters below."
      }),
      JsxRuntime.jsxs("label", {
        children: [
          "Pairing code",
          JsxRuntime.jsx("input", {
            spellCheck: false,
            autoComplete: "off",
            autoCapitalize: "characters",
            autoFocus: true,
            maxLength: 5,
            type: "text",
            value: code,
            onChange: ev => setCode(param => ev.target.value)
          })
        ]
      }),
      error !== undefined ? JsxRuntime.jsx("p", {
          children: error,
          className: "efb-mirror-pairing-error"
        }) : null,
      JsxRuntime.jsx("button", {
        children: busy ? "Pairing…" : "Pair",
        disabled: busy,
        type: "submit"
      })
    ],
    className: "efb-mirror-pairing",
    onSubmit: onSubmit
  });
}

let make = EfbPairing;

export {
  storageKey,
  readStored,
  writeStored,
  clearStored,
  unpairAndReload,
  defaultUrlFromLocation,
  _parseQueryCreds,
  _parseQueryCode,
  readQueryCreds,
  readQueryCode,
  redeemPairingCode,
  stripQuery,
  make,
}
/* redeemPairingCode Not a pure module */
