// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Core__Dict from "@rescript/core/src/Core__Dict.res.mjs";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";

function make() {
  return {
    sim: {
      values: {},
      subs: {}
    },
    ui: {
      values: {},
      subs: {}
    },
    wildcardSim: [],
    wildcardUi: []
  };
}

function channelOf(store, ch) {
  if (ch === "sim") {
    return store.sim;
  } else {
    return store.ui;
  }
}

function read(store, ch, key) {
  return (
      ch === "sim" ? store.sim : store.ui
    ).values[key];
}

function notify(subs) {
  let len = subs.length;
  for (let i = 0; i < len; ++i) {
    let l = subs[i];
    l();
  }
}

function subscribe(store, ch, key, l) {
  let d = ch === "sim" ? store.sim : store.ui;
  let a = d.subs[key];
  let arr;
  if (a !== undefined) {
    arr = a;
  } else {
    let a$1 = [];
    d.subs[key] = a$1;
    arr = a$1;
  }
  arr.push(l);
  return () => {
    let idx = arr.indexOf(l);
    if (idx >= 0) {
      arr.splice(idx, 1);
      return;
    }
  };
}

function subscribeChannel(store, ch, l) {
  if (ch === "sim") {
    store.wildcardSim.push(l);
    return () => {
      let idx = store.wildcardSim.indexOf(l);
      if (idx >= 0) {
        store.wildcardSim = store.wildcardSim.filter((param, i) => i !== idx);
        return;
      }
    };
  } else {
    store.wildcardUi.push(l);
    return () => {
      let idx = store.wildcardUi.indexOf(l);
      if (idx >= 0) {
        store.wildcardUi = store.wildcardUi.filter((param, i) => i !== idx);
        return;
      }
    };
  }
}

function jsonEq(a, b) {
  return JSON.stringify(a) === JSON.stringify(b);
}

function applyDelta(store, ch, data) {
  let d = ch === "sim" ? store.sim : store.ui;
  let changedAny = {
    contents: false
  };
  Object.entries(data).forEach(param => {
    let v = param[1];
    let k = param[0];
    let isNull = Core__JSON.Classify.classify(v) === "Null";
    let prev = d.values[k];
    let changed = prev !== undefined ? (
        isNull ? true : JSON.stringify(prev) !== JSON.stringify(v)
      ) : !isNull;
    if (!changed) {
      return;
    }
    if (isNull) {
      Core__Dict.$$delete(d.values, k);
    } else {
      d.values[k] = v;
    }
    let subs = d.subs[k];
    if (subs !== undefined) {
      notify(subs);
    }
    changedAny.contents = true;
  });
  if (changedAny.contents) {
    return notify(ch === "sim" ? store.wildcardSim : store.wildcardUi);
  }
}

function applySnapshot(store, sim, ui) {
  let mergedSim = {};
  Object.keys(store.sim.values).forEach(k => {
    if (!Core__Option.isSome(sim[k])) {
      mergedSim[k] = null;
      return;
    }
  });
  Object.entries(sim).forEach(param => {
    mergedSim[param[0]] = param[1];
  });
  applyDelta(store, "sim", mergedSim);
  let mergedUi = {};
  Object.keys(store.ui.values).forEach(k => {
    if (!Core__Option.isSome(ui[k])) {
      mergedUi[k] = null;
      return;
    }
  });
  Object.entries(ui).forEach(param => {
    mergedUi[param[0]] = param[1];
  });
  applyDelta(store, "ui", mergedUi);
}

export {
  make,
  channelOf,
  read,
  notify,
  subscribe,
  subscribeChannel,
  jsonEq,
  applyDelta,
  applySnapshot,
}
/* No side effect */
