// Generated by ReScript, PLEASE EDIT WITH CARE

import * as EfbStore from "./EfbStore.res.mjs";
import * as WebSocket from "./WebSocket.res.mjs";
import * as Core__JSON from "@rescript/core/src/Core__JSON.res.mjs";
import * as Core__Option from "@rescript/core/src/Core__Option.res.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function onConnectionChange(t, l) {
  t.connectionListeners.push(l);
  return () => {
    t.connectionListeners = t.connectionListeners.filter(x => !Object.is(x, l));
  };
}

function getConnection(t) {
  return t.connection;
}

function setConnection(t, c) {
  t.connection = c;
  EfbStore.notify(t.connectionListeners);
}

function onCmd(t, name, h) {
  let a = t.cmdListeners[name];
  let arr;
  if (a !== undefined) {
    arr = a;
  } else {
    let a$1 = [];
    t.cmdListeners[name] = a$1;
    arr = a$1;
  }
  arr.push(h);
  return () => {
    let idx = arr.indexOf(h);
    if (idx >= 0) {
      arr.splice(idx, 1);
      return;
    }
  };
}

function dictOf(j) {
  let d = Core__JSON.Decode.object(j);
  if (d !== undefined) {
    return d;
  } else {
    return {};
  }
}

function handleFrame(t, raw) {
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (exn) {
    parsed = null;
  }
  let o = Core__JSON.Decode.object(parsed);
  let obj = o !== undefined ? o : ({});
  let kind = Core__Option.getOr(Core__Option.flatMap(obj["t"], Core__JSON.Decode.string), "");
  switch (kind) {
    case "cmd" :
      let name = Core__Option.getOr(Core__Option.flatMap(obj["name"], Core__JSON.Decode.string), "");
      let data = Core__Option.getOr(obj["data"], null);
      if (name === "") {
        return;
      }
      let hs = t.cmdListeners[name];
      if (hs !== undefined) {
        hs.forEach(h => h(name, data));
        return;
      } else {
        return;
      }
    case "pong" :
      return;
    case "sim" :
      let data$1 = Core__Option.getOr(Core__Option.map(obj["data"], dictOf), {});
      return EfbStore.applyDelta(t.store, "sim", data$1);
    case "snapshot" :
      let sim = Core__Option.getOr(Core__Option.map(obj["sim"], dictOf), {});
      let ui = Core__Option.getOr(Core__Option.map(obj["ui"], dictOf), {});
      return EfbStore.applySnapshot(t.store, sim, ui);
    case "ui" :
      let data$2 = Core__Option.getOr(Core__Option.map(obj["data"], dictOf), {});
      return EfbStore.applyDelta(t.store, "ui", data$2);
    default:
      console.warn("efb-mirror: unknown frame type", kind);
      return;
  }
}

function connect(t) {
  if (t.closed) {
    return;
  }
  setConnection(t, "Connecting");
  let url = t.url + `?token=` + t.token;
  let ws = new (window.WebSocket)(url);
  t.socket = Primitive_option.some(ws);
  WebSocket.addOpenListener(ws, param => {
    t.retry = 0;
    setConnection(t, "Open");
  });
  WebSocket.addMessageListener(ws, ev => {
    let raw = ev.data;
    let s = Core__JSON.Classify.classify(raw);
    if (typeof s !== "object" || s.TAG !== "String") {
      return;
    } else {
      return handleFrame(t, s._0);
    }
  });
  WebSocket.addCloseListener(ws, param => {
    t.socket = undefined;
    setConnection(t, "Closed");
    if (t.closed) {
      return;
    }
    let delay = Math.min(30000.0, 500.0 * Math.pow(2.0, t.retry));
    t.retry = t.retry + 1 | 0;
    setTimeout(() => connect(t), delay | 0);
  });
  WebSocket.addErrorListener(ws, param => {});
}

function make(store, url, token) {
  let t = {
    store: store,
    socket: undefined,
    closed: false,
    retry: 0,
    connection: "Closed",
    connectionListeners: [],
    cmdListeners: {},
    url: url,
    token: token
  };
  connect(t);
  return t;
}

function close(t) {
  t.closed = true;
  let ws = t.socket;
  if (ws !== undefined) {
    Primitive_option.valFromOption(ws).close();
    t.socket = undefined;
  }
  setConnection(t, "Closed");
}

function sendRaw(t, payload) {
  let ws = t.socket;
  if (ws !== undefined && t.connection === "Open") {
    Primitive_option.valFromOption(ws).send(payload);
  } else {
    console.warn("efb-mirror: send before open; dropped");
  }
}

function sendUi(t, key, value) {
  let data = {};
  data[key] = value;
  let frame = {};
  frame["t"] = "ui";
  frame["data"] = data;
  sendRaw(t, JSON.stringify(frame));
}

function sendSim(t, key, value) {
  let data = {};
  data[key] = value;
  let frame = {};
  frame["t"] = "sim";
  frame["data"] = data;
  sendRaw(t, JSON.stringify(frame));
}

function sendCmd(t, name, data) {
  let frame = {};
  frame["t"] = "cmd";
  frame["name"] = name;
  frame["data"] = data;
  sendRaw(t, JSON.stringify(frame));
}

function sendPing(t) {
  let frame = {};
  frame["t"] = "ping";
  sendRaw(t, JSON.stringify(frame));
}

export {
  onConnectionChange,
  getConnection,
  setConnection,
  onCmd,
  dictOf,
  handleFrame,
  connect,
  make,
  close,
  sendRaw,
  sendUi,
  sendSim,
  sendCmd,
  sendPing,
}
/* WebSocket Not a pure module */
