// Generated by ReScript, PLEASE EDIT WITH CARE


let MessageEvent = {};

function _efb_addOpen(ws, cb) { ws.addEventListener("open", cb); }
function _efb_addClose(ws, cb) { ws.addEventListener("close", cb); }
function _efb_addError(ws, cb) { ws.addEventListener("error", cb); }
function _efb_addMessage(ws, cb) { ws.addEventListener("message", cb); }
;

let addOpenListener = _efb_addOpen;

let addCloseListener = _efb_addClose;

let addErrorListener = _efb_addError;

let addMessageListener = _efb_addMessage;

export {
  MessageEvent,
  addOpenListener,
  addCloseListener,
  addErrorListener,
  addMessageListener,
}
/*  Not a pure module */
